project:
  type: website
  output-dir: docs

website: 
  title: "Group 21-Xiaolu Ji"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual




